Repository Minibuz/Banxxy, pull requests merged in 2023-01, with the labels that each got.

#5 docs: readme
  README.md
Labels: documentation

#13 Insertion of data into the database
  bdd/start.sh
Labels: database

#11 feat: get detail for an account for an id provided
  backend/src/main/java/fr/esipe/banxxy/controller/AccountController.java
  backend/src/main/java/fr/esipe/banxxy/dao/AccountEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/CustomerEntity.java
  backend/src/main/java/fr/esipe/banxxy/dto/AccountDto.java
  backend/src/main/java/fr/esipe/banxxy/repository/UserRepository.java
  backend/src/main/java/fr/esipe/banxxy/service/AccountService.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
  frontend/package-lock.json
Labels: enhancement

#15 Accounts api
  backend/src/main/java/fr/esipe/banxxy/controller/AccountsController.java
  backend/src/main/java/fr/esipe/banxxy/service/AccountsService.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountsServicesImpl.java
Labels: enhancement

#16 Database connexion, entities and repositories
  backend/src/main/java/fr/esipe/banxxy/dao/AccountEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/TransactionEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/UserEntity.java
  backend/src/main/java/fr/esipe/banxxy/repository/AccountRepository.java
  backend/src/main/java/fr/esipe/banxxy/repository/AdvisorRepository.java
  backend/src/main/java/fr/esipe/banxxy/repository/CustomerRepository.java
  backend/src/main/java/fr/esipe/banxxy/repository/TransactionRepository.java
  backend/src/main/java/fr/esipe/banxxy/repository/UserRepository.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
  backend/src/main/resources/application.properties
  docker-compose.yml
Labels: bug, database

#12 Front dashboard Advisor
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SearchBar.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/HomePage.vue
Labels: enhancement

#29 fix: TransactionDto && Id type
  backend/src/main/java/fr/esipe/banxxy/controller/TransactionController.java
  backend/src/main/java/fr/esipe/banxxy/dto/TransactionDto.java
  backend/src/main/java/fr/esipe/banxxy/service/TransactionService.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/TransactionServiceImpl.java
Labels: bug, enhancement

#30 feat: getUser / createCustomer
  backend/src/main/java/fr/esipe/banxxy/controller/UserController.java
  backend/src/main/java/fr/esipe/banxxy/dto/UserDetailDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/UserDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/UserReceivedDto.java
  backend/src/main/java/fr/esipe/banxxy/service/UserService.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/UserServicesImpl.java
Labels: bug, enhancement, help wanted

#20 feat: component to create a user
  frontend/package-lock.json
  frontend/src/router/index.js
  frontend/src/services/customer.create.js
  frontend/src/views/CustomerCreation.vue
  frontend/src/views/HelloWorld.vue
Labels: enhancement

#28 Spring security - Login & Check permissions
  backend/pom.xml
  backend/src/main/java/fr/esipe/banxxy/configuration/TokenManager.java
  backend/src/main/java/fr/esipe/banxxy/configuration/WebSecurityConfiguration.java
  backend/src/main/java/fr/esipe/banxxy/configuration/jwt/AuthEntryPointJwt.java
  backend/src/main/java/fr/esipe/banxxy/configuration/jwt/AuthTokenFilter.java
  backend/src/main/java/fr/esipe/banxxy/configuration/jwt/JwtUtils.java
  backend/src/main/java/fr/esipe/banxxy/configuration/services/UserDetailsImpl.java
  backend/src/main/java/fr/esipe/banxxy/configuration/services/UserDetailsServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/controller/AuthController.java
  backend/src/main/java/fr/esipe/banxxy/controller/Controller.java
  backend/src/main/java/fr/esipe/banxxy/controller/TestController.java
  backend/src/main/java/fr/esipe/banxxy/dao/ERole.java
  backend/src/main/java/fr/esipe/banxxy/dao/UserEntity.java
  backend/src/main/java/fr/esipe/banxxy/dto/request/LoginRequest.java
  backend/src/main/java/fr/esipe/banxxy/dto/response/JwtResponse.java
  backend/src/main/java/fr/esipe/banxxy/repository/UserRepository.java
  backend/src/main/resources/application.properties
  bdd/start.sh
Labels: enhancement

#47 Swagger
  backend/pom.xml
  backend/src/main/java/fr/esipe/banxxy/configuration/SpringFoxConfig.java
  backend/src/main/java/fr/esipe/banxxy/controller/AuthentificationController.java
  backend/src/main/java/fr/esipe/banxxy/controller/RedirectionController.java
  backend/src/main/java/fr/esipe/banxxy/controller/TestController.java
  backend/src/main/resources/application.properties
Labels: documentation, enhancement

#58 Bug fix & clean code
  backend/pom.xml
  backend/src/main/java/fr/esipe/banxxy/BanxxyAplication.java
  backend/src/main/java/fr/esipe/banxxy/configuration/JmsManager.java
  backend/src/main/java/fr/esipe/banxxy/configuration/JmsReceiver.java
  backend/src/main/java/fr/esipe/banxxy/configuration/WebSecurityConfiguration.java
  backend/src/main/java/fr/esipe/banxxy/configuration/services/UserDetailsServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/controller/AccountController.java
  backend/src/main/java/fr/esipe/banxxy/controller/AccountsController.java
  backend/src/main/java/fr/esipe/banxxy/controller/AuthentificationController.java
  backend/src/main/java/fr/esipe/banxxy/controller/RedirectionController.java
  backend/src/main/java/fr/esipe/banxxy/controller/TransactionController.java
  backend/src/main/java/fr/esipe/banxxy/controller/UserController.java
  backend/src/main/java/fr/esipe/banxxy/dto/TestDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/account/AccountDetailedDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/account/AccountDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/account/AccountsChildrenDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/account/AccountsParentDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/auth/request/LoginRequest.java
  backend/src/main/java/fr/esipe/banxxy/dto/auth/response/JwtResponse.java
  backend/src/main/java/fr/esipe/banxxy/dto/jms/Log.java
  backend/src/main/java/fr/esipe/banxxy/dto/transaction/TransactionDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/user/UserDetailDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/user/UserDto.java
  backend/src/main/java/fr/esipe/banxxy/dto/user/UserReceivedDto.java
  backend/src/main/java/fr/esipe/banxxy/service/AccountService.java
  backend/src/main/java/fr/esipe/banxxy/service/AccountsService.java
  backend/src/main/java/fr/esipe/banxxy/service/EmailSenderService.java
  backend/src/main/java/fr/esipe/banxxy/service/TestService.java
  backend/src/main/java/fr/esipe/banxxy/service/TransactionService.java
  backend/src/main/java/fr/esipe/banxxy/service/UserService.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/AccountsServicesImpl.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/EmailSenderServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/TransactionServiceImpl.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/UserServicesImpl.java
  backend/src/main/resources/META-INF/MANIFEST.MF
  backend/src/main/resources/application.properties
Labels: bug, documentation, enhancement

#64 Database
  bdd/start.sh
Labels: database

#73 Jms log
  backend/src/main/java/fr/esipe/banxxy/configuration/JmsReceiver.java
  backend/src/main/java/fr/esipe/banxxy/controller/RedirectionController.java
  backend/src/main/java/fr/esipe/banxxy/dto/jms/Log.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/TransactionsServiceImpl.java
Labels: bug, enhancement

#74 Jms log
  backend/src/main/java/fr/esipe/banxxy/controller/JmsController.java
  backend/src/main/java/fr/esipe/banxxy/controller/RedirectionController.java
Labels: bug

#76 Date fix jackson
  backend/src/main/java/fr/esipe/banxxy/controller/JmsController.java
  backend/src/main/java/fr/esipe/banxxy/dto/jms/Log.java
Labels: bug

#77 feat : token JWT delete when timeout + fix bug in loginPage
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/utils/index.js
  frontend/src/views/LoginPage.vue
Labels: bug

#80 Some last second fix
  backend/src/main/java/fr/esipe/banxxy/configuration/jwt/AuthTokenFilter.java
  backend/src/main/java/fr/esipe/banxxy/controller/UserController.java
  backend/src/main/java/fr/esipe/banxxy/service/impl/UserServicesImpl.java
  backend/src/main/resources/application.properties
Labels: bug

#79 Docs
  backend/src/main/java/fr/esipe/banxxy/dao/AccountEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/AdvisorEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/CustomerEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/TransactionEntity.java
  backend/src/main/java/fr/esipe/banxxy/dao/UserEntity.java
Labels: documentation

#82 Emergency patch
  backend/src/main/java/fr/esipe/banxxy/dao/UserEntity.java
  backend/src/main/resources/application.properties
Labels: bug
